resolution: 512
num_generated_frames_per_clip: 4
fps: 30
num_init_past_frames: 2
num_past_frames: 4
inference_steps: 4
cfg_scale: 3.5
#weight_dtype: bf16
weight_dtype: fp16
enable_xformers_memory_efficient_attention: true

model_name_or_path: ../../models/memo
#model_name_or_path: checkpoints
#vae: stabilityai/sd-vae-ft-mse
vae: ../../models/memo/stabilityai/sd-vae-ft-mse
wav2vec: ../../models/memo/facebook/wav2vec2-base-960h
emotion2vec: ../../models/memo/iic/emotion2vec_plus_large
misc_model_dir: checkpoints
